project:
  type: website
  output-dir: docs

website:
  title: "STV1020"
  page-navigation: true
  sidebar:
    search: false
    contents:
      - index.qmd
      - installasjon.qmd
      - laste_data.qmd
      - workbench.qmd
      - proveinfo.qmd

format:
  html:
    theme: lux
    highlight-style: zenburn
    toc: true