project:
  type: website
  output-dir: .
  

website:
  title: "STV1020"
  page-navigation: true
  sidebar:
    search: false
    contents:
      - section: "Informasjon"
        contents: 
          - index.qmd
          - installasjon.qmd
          - rogrstudio.qmd
          - laste_data.qmd
          - workbench.qmd
          - proveinfo.qmd
      - section: "Seminarer"
        contents:
          - seminar/seminar1.qmd
          - seminar/seminar2.qmd
          - seminar/seminar3.qmd
          - seminar/seminar4.qmd
          - seminar/seminar5.qmd
          - seminar/seminar6.qmd

      
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    highlight-style: zenburn
    toc: true
    mainfont: expressway
    monobackgroundcolor: "#E3E3E3"