project:
  type: website
  output-dir: docs
  

website:
  title: "STV1020"
  page-navigation: true
  sidebar:
    search: true
    contents:
      - index.qmd
      - section: "Informasjon"
        contents: 
          - installasjon.qmd
          - rogrstudio.qmd
          - laste_data.qmd
          - workbench.qmd
          - proveinfo.qmd
      - section: "Seminarer"
        contents:
          - seminar/seminar1.qmd
          - seminar/seminar2.qmd
          - seminar/seminar3.qmd
          - seminar/seminar4.qmd
          - seminar/seminar5.qmd
          - seminar/seminar6.qmd
      - section: "Oppgaver"
        contents:
          - oppgaver/oppgaver1.qmd
          - oppgaver/oppgaver2.qmd
          - oppgaver/oppgaver3.qmd
          - oppgaver/oppgaver4.qmd
          - oppgaver/oppgaver5.qmd
          - oppgaver/oppgaver6.qmd
    tools:       
      - icon: github
        menu:
          - text: "Kildekode"
            url:  https://github.com/martigso/STV1020
          - text: "Meld fra om feil"
            url:  mailto:martin.soyland@stv.uio.no
      
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    highlight-style: zenburn
    toc: true
    mainfont: expressway
    monobackgroundcolor: "#E3E3E3"